version: 1.0

language: node_js

node_js:
  - '12'
  - '14'

branches:
  only:
    - master

install: yarn --no-progress --frozen-lockfile --ignore-engines

cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - yarn test-ci

deploy:
  edge: true
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_API_TOKEN'
  skip_cleanup: true
  on:
    branch: master
